#!/bin/sh
dotfiles=".ackrc .bashrc .gitconfig .hgrc .synergy.conf .tmux.conf"
cd $HOME
for f in $dotfiles; do
    ln -sf .files/$f;
done;
# the command below will sometime lock up during automated deployments
