#!/bin/sh
dotfiles=".ackrc .bash_aliases .bashrc .gitconfig .hgrc .synergy.conf .tmux.conf .bash-git"
cd $HOME
for f in $dotfiles; do
    ln -sf dotfiles/$f;
done;
# the command below will sometime lock up during automated deployments
vim +BundleInstall +qall &>/dev/null
