#!/bin/sh
dotfiles=".ackrc .bash_aliases .bash_include .bashrc .gitconfig .hgrc .synergy.conf .tmux.conf .bash-git"
cd $HOME
for f in $dotfiles; do
    ln -sf .files/$f;
done;
# the command below will sometime lock up during automated deployments
